version: 2
jobs:
  build:
    working_directory: ~/styx
    docker:
      - image: maven:3.5.0-jdk-8
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline compile
      - save_cache:
          key: v1-deps-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2
      - run: mvn verify
      - run: bash <(curl -s https://codecov.io/bash -f '!./report/target/site/jacoco-aggregate/jacoco.xml')
      - run: |
          mkdir test-reports
          find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} test-reports/ \;
      - store_test_results:
          path: test-reports/
      - store_artifacts:
          path: report/target/site/jacoco-aggregate/
          destination: jacoco-aggregate
